all:	egpaper_for_review.tex 
	pdflatex egpaper_for_review.tex 
	bibtex egpaper_for_review
	pdflatex egpaper_for_review.tex 
	pdflatex egpaper_for_review.tex 

pdf: 	egpaper_for_review.tex
	pdflatex egpaper_for_review.tex 

bib:	egpaper_for_review.tex
	pdflatex egpaper_for_review.tex 
	bibtex egpaper_for_review
